using System.ComponentModel.DataAnnotations;
using CommunityToolkit.Mvvm.ComponentModel;

namespace CSharp14FieldKeywordWpf.Models;

/// <summary>
/// Represents a user profile using CommunityToolkit.MVVM source generators.
/// Demonstrates the modern approach with ObservableProperty attributes on partial properties.
/// </summary>
public partial class UserProfile : ObservableObject
{
    /// <summary>
    /// First name with validation using ObservableProperty - cleaner syntax
    /// </summary>
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(FullName))]
    public partial string FirstName { get; set; } = string.Empty;

    /// <summary>
    /// Last name with validation using ObservableProperty - cleaner syntax
    /// </summary>
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(FullName))]
    public partial string LastName { get; set; } = string.Empty;

    /// <summary>
    /// Email with validation using ObservableProperty - cleaner syntax
    /// </summary>
    [ObservableProperty]
    public partial string Email { get; set; } = string.Empty;

    /// <summary>
    /// Age with range validation using ObservableProperty - cleaner syntax
    /// </summary>
    [ObservableProperty]
    public partial int Age { get; set; }

    /// <summary>
    /// Salary with validation using ObservableProperty - cleaner syntax
    /// </summary>
    [ObservableProperty]
    public partial decimal Salary { get; set; }

    /// <summary>
    /// Active status using ObservableProperty - simplified
    /// </summary>
    [ObservableProperty]
    public partial bool IsActive { get; set; } = true;

    /// <summary>
    /// Last login date with auto-update using ObservableProperty
    /// </summary>
    [ObservableProperty]
    public partial DateTime LastLoginDate { get; set; } = DateTime.Now;

    /// <summary>
    /// Computed full name property - no field needed
    /// </summary>
    public string FullName => $"{FirstName} {LastName}";

    /// <summary>
    /// Method to update last login to current time
    /// </summary>
    public void UpdateLastLogin()
    {
        LastLoginDate = DateTime.Now;
    }

    // Validation methods using partial methods generated by source generator
    partial void OnFirstNameChanging(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
            throw new ArgumentException("First name cannot be empty");
    }

    partial void OnLastNameChanging(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
            throw new ArgumentException("Last name cannot be empty");
    }

    partial void OnEmailChanging(string value)
    {
        if (string.IsNullOrWhiteSpace(value) || !new EmailAddressAttribute().IsValid(value))
            throw new ArgumentException("Invalid email address");
    }

    partial void OnAgeChanging(int value)
    {
        if (value < 0 || value > 150)
            throw new ArgumentOutOfRangeException(nameof(value), "Age must be between 0 and 150");
    }

    partial void OnSalaryChanging(decimal value)
    {
        if (value < 0)
            throw new ArgumentOutOfRangeException(nameof(value), "Salary cannot be negative");
    }
}